import "dotenv/config";
import { neon } from "@neondatabase/serverless";
import { drizzle } from "drizzle-orm/neon-http";
import { games, apkVersions } from "../src/lib/db/schema";

const sql = neon(process.env.DATABASE_URL!);
const db = drizzle({ client: sql });

const sampleGames = [
  {
    slug: "788win-game-download-apk",
    title: "788win Game",
    description: "788win is Pakistan's top-rated casino and earning app with 300+ slots, live dealer games, and instant JazzCash withdrawals. Get a 500% welcome bonus on your first deposit.",
    version: "v2.1.0",
    fileSize: "150 MB",
    downloadCount: 520000,
    rating: "4.2",
    totalVotes: 1842,
    category: "casino-games" as const,
    osRequirements: "Android 7.0+ / iOS 12+",
    iconUrl: "/images/games/788win-icon.webp",
    downloadUrl: "https://example.com/download/788win",
    isNew: false,
    isUpdated: true,
    isFeatured: true,
    publishedAt: new Date("2025-11-01"),
    updatedAt: new Date("2026-04-10"),
    seoTitle: "788win Game Download APK 2026 – Free Casino App Pakistan",
    seoDescription: "Download 788win Game APK for Pakistan. Get 500% welcome bonus, 300+ slots, JazzCash withdrawals. Safe & verified APK download guide.",
    tags: ["788win", "casino", "pakistan", "earning app", "apk download", "slots"],
  },
  {
    slug: "qz786-app-download-apk",
    title: "QZ786 App",
    description: "QZ786 is a feature-rich earning app offering color prediction, dice, and aviator games with Easypaisa support.",
    version: "v3.0.2",
    fileSize: "85 MB",
    downloadCount: 340000,
    rating: "4.0",
    totalVotes: 1250,
    category: "earning-apps" as const,
    osRequirements: "Android 6.0+ / iOS 13+",
    iconUrl: "/images/games/qz786-icon.webp",
    downloadUrl: "https://example.com/download/qz786",
    isNew: false,
    isUpdated: false,
    isFeatured: true,
    publishedAt: new Date("2025-09-15"),
    updatedAt: new Date("2026-03-20"),
    seoTitle: "QZ786 App Download APK 2026 – Earning App Pakistan",
    seoDescription: "Download QZ786 APK. Color prediction, dice & aviator games. Earn real money with Easypaisa withdrawals in Pakistan.",
    tags: ["qz786", "earning", "pakistan", "color prediction", "apk download"],
  },
  {
    slug: "pk3-game-download-apk",
    title: "PK3 Game",
    description: "PK3 is a popular Pakistani gaming platform with rummy, poker, and teen patti. Supports JazzCash deposits.",
    version: "v1.8.5",
    fileSize: "120 MB",
    downloadCount: 290000,
    rating: "4.3",
    totalVotes: 980,
    category: "casino-games" as const,
    osRequirements: "Android 7.0+ / iOS 12+",
    iconUrl: "/images/games/pk3-icon.webp",
    downloadUrl: "https://example.com/download/pk3",
    isNew: false,
    isUpdated: true,
    isFeatured: true,
    publishedAt: new Date("2025-08-20"),
    updatedAt: new Date("2026-04-05"),
    seoTitle: "PK3 Game Download APK 2026 – Rummy & Poker Pakistan",
    seoDescription: "Download PK3 Game APK for Pakistan. Play rummy, poker & teen patti. JazzCash deposits accepted. Safe download.",
    tags: ["pk3", "casino", "rummy", "poker", "pakistan", "apk download"],
  },
  {
    slug: "777taz-game-download-apk",
    title: "777Taz Game",
    description: "777Taz brings Vegas-style slots to Pakistan with progressive jackpots and daily free spins for new players.",
    version: "v4.2.1",
    fileSize: "200 MB",
    downloadCount: 180000,
    rating: "3.9",
    totalVotes: 720,
    category: "casino-games" as const,
    osRequirements: "Android 8.0+ / iOS 14+",
    iconUrl: "/images/games/777taz-icon.webp",
    downloadUrl: "https://example.com/download/777taz",
    isNew: true,
    isUpdated: false,
    isFeatured: false,
    publishedAt: new Date("2026-03-01"),
    updatedAt: new Date("2026-03-01"),
    seoTitle: "777Taz Game Download APK 2026 – Vegas Slots Pakistan",
    seoDescription: "Download 777Taz APK. Vegas-style slots with progressive jackpots and daily free spins. Available for Android & iOS.",
    tags: ["777taz", "casino", "slots", "pakistan", "jackpot"],
  },
  {
    slug: "noob-win-app-download-apk",
    title: "Noob Win",
    description: "Noob Win is a beginner-friendly earning app with simple tasks, surveys, and mini-games that pay via Easypaisa.",
    version: "v2.5.0",
    fileSize: "45 MB",
    downloadCount: 410000,
    rating: "4.1",
    totalVotes: 2100,
    category: "earning-apps" as const,
    osRequirements: "Android 5.0+ / iOS 11+",
    iconUrl: "/images/games/noob-win-icon.webp",
    downloadUrl: "https://example.com/download/noob-win",
    isNew: false,
    isUpdated: true,
    isFeatured: true,
    publishedAt: new Date("2025-06-10"),
    updatedAt: new Date("2026-04-01"),
    seoTitle: "Noob Win Download APK 2026 – Easy Earning App Pakistan",
    seoDescription: "Download Noob Win APK. Earn money with simple tasks & mini-games. Easypaisa withdrawals available in Pakistan.",
    tags: ["noob win", "earning", "tasks", "pakistan", "easypaisa", "beginner"],
  },
  {
    slug: "zd22-game-download-apk",
    title: "ZD22 Game",
    description: "ZD22 offers live sports betting and casino games in one platform with competitive odds for Pakistani users.",
    version: "v1.3.0",
    fileSize: "95 MB",
    downloadCount: 150000,
    rating: "3.8",
    totalVotes: 530,
    category: "casino-games" as const,
    osRequirements: "Android 7.0+ / iOS 13+",
    iconUrl: "/images/games/zd22-icon.webp",
    downloadUrl: "https://example.com/download/zd22",
    isNew: false,
    isUpdated: false,
    isFeatured: false,
    publishedAt: new Date("2025-10-10"),
    updatedAt: new Date("2026-02-15"),
    seoTitle: "ZD22 Game Download APK 2026 – Sports Betting Pakistan",
    seoDescription: "Download ZD22 APK for Pakistan. Live sports betting & casino games with competitive odds. Safe & verified download.",
    tags: ["zd22", "casino", "sports betting", "pakistan", "live"],
  },
  {
    slug: "877bet-game-download-apk",
    title: "877Bet Game",
    description: "877Bet is a premium betting platform with cricket betting, live casino, and instant bank transfers for Pakistan.",
    version: "v5.1.0",
    fileSize: "175 MB",
    downloadCount: 260000,
    rating: "4.4",
    totalVotes: 1580,
    category: "casino-games" as const,
    osRequirements: "Android 8.0+ / iOS 14+",
    iconUrl: "/images/games/877bet-icon.webp",
    downloadUrl: "https://example.com/download/877bet",
    isNew: false,
    isUpdated: true,
    isFeatured: true,
    publishedAt: new Date("2025-07-20"),
    updatedAt: new Date("2026-04-08"),
    seoTitle: "877Bet Game Download APK 2026 – Cricket Betting Pakistan",
    seoDescription: "Download 877Bet APK. Cricket betting, live casino & instant bank transfers in Pakistan. Premium betting experience.",
    tags: ["877bet", "casino", "cricket", "betting", "pakistan", "live casino"],
  },
  {
    slug: "588win-game-download-apk",
    title: "588win Game",
    description: "588win features 200+ slot machines, fish shooting games, and weekly tournaments with PKR prize pools.",
    version: "v3.7.2",
    fileSize: "160 MB",
    downloadCount: 195000,
    rating: "4.0",
    totalVotes: 870,
    category: "casino-games" as const,
    osRequirements: "Android 7.0+ / iOS 12+",
    iconUrl: "/images/games/588win-icon.webp",
    downloadUrl: "https://example.com/download/588win",
    isNew: false,
    isUpdated: false,
    isFeatured: false,
    publishedAt: new Date("2025-12-05"),
    updatedAt: new Date("2026-03-10"),
    seoTitle: "588win Game Download APK 2026 – Slots & Fish Shooting Pakistan",
    seoDescription: "Download 588win APK. 200+ slot machines, fish shooting games & weekly tournaments. Available in Pakistan.",
    tags: ["588win", "casino", "slots", "fish shooting", "pakistan"],
  },
  {
    slug: "luckbat7-app-download-apk",
    title: "LuckBat7",
    description: "LuckBat7 is a luck-based earning app with scratch cards, spin wheels, and daily check-in rewards for Pakistani users.",
    version: "v1.2.0",
    fileSize: "35 MB",
    downloadCount: 320000,
    rating: "3.7",
    totalVotes: 1430,
    category: "earning-apps" as const,
    osRequirements: "Android 5.0+ / iOS 11+",
    iconUrl: "/images/games/luckbat7-icon.webp",
    downloadUrl: "https://example.com/download/luckbat7",
    isNew: true,
    isUpdated: false,
    isFeatured: false,
    publishedAt: new Date("2026-02-14"),
    updatedAt: new Date("2026-02-14"),
    seoTitle: "LuckBat7 Download APK 2026 – Scratch & Win Pakistan",
    seoDescription: "Download LuckBat7 APK. Scratch cards, spin wheels & daily rewards. Earn real money in Pakistan.",
    tags: ["luckbat7", "earning", "scratch cards", "spin", "pakistan"],
  },
  {
    slug: "done55-app-download-apk",
    title: "Done55",
    description: "Done55 is a task-based earning platform where users complete offers, watch ads, and refer friends to earn via JazzCash.",
    version: "v2.0.3",
    fileSize: "55 MB",
    downloadCount: 275000,
    rating: "3.6",
    totalVotes: 940,
    category: "earning-apps" as const,
    osRequirements: "Android 6.0+ / iOS 12+",
    iconUrl: "/images/games/done55-icon.webp",
    downloadUrl: "https://example.com/download/done55",
    isNew: false,
    isUpdated: true,
    isFeatured: false,
    publishedAt: new Date("2025-11-20"),
    updatedAt: new Date("2026-03-28"),
    seoTitle: "Done55 Download APK 2026 – Task Earning App Pakistan",
    seoDescription: "Download Done55 APK. Complete tasks, watch ads & refer friends. Earn via JazzCash in Pakistan.",
    tags: ["done55", "earning", "tasks", "referral", "jazzcash", "pakistan"],
  },
];

async function seed() {
  console.log("Seeding database...");

  for (const game of sampleGames) {
    const [inserted] = await db.insert(games).values(game).returning({ id: games.id });
    console.log(`Inserted: ${game.title} (id: ${inserted.id})`);

    await db.insert(apkVersions).values([
      {
        gameId: inserted.id,
        version: game.version,
        releaseDate: game.updatedAt.toISOString().split("T")[0],
        changelog: "Latest stable release with bug fixes and performance improvements.",
      },
      {
        gameId: inserted.id,
        version: game.version.replace(/\d+$/, (n) => String(Number(n) - 1)),
        releaseDate: new Date(game.updatedAt.getTime() - 30 * 86400000).toISOString().split("T")[0],
        changelog: "Previous version with minor updates.",
      },
    ]);
  }

  console.log("Seeding complete!");
}

seed().catch(console.error);
